### PR TITLE
Kawa darkmode+c

### PR DESCRIPTION
**Pull request by kawaMANMI**
## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Write a summary of your change. Explain why you have made it.
1-Logut and  user anem items for navbar added
2. some css fro nav bar + login + footer added
3. Dark mode for Header and footer completed
4. Forgetpassword deactivated for now
5. subscribe section in footer added

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

### CODE REVIEW

**Review by hayatu4islam — APPROVED** [review]

**Comment by hayatu4islam** [comment]
It seems the lint check failed. We have two pull requests almost the same time.

**Review by irinamihai150 — APPROVED** [review]

**Comment by irinamihai150** [comment]
@kawaMANMI I aproved this but idont merge it until you fixed the last issue

**Comment by hayatu4islam** [comment]
The deploy for web service starter-kit has failed. We may need to check the codes again.

**Comment by kawaMANMI** [comment]
Ok just checked and pushed again

**Pull request merged**
